### ISSUE TITLE
Custom primary key - not 'id'

### ISSUE THREAD

**Issue by p2c2e** [lalalilo/express-sequelize-crud#56]
Nice library. Thanks for that. I notice that if we define a custom primary key, some part of the library breaks due to assumption that an 'id' column exists. 

I took a look at the code - for example in the getList flow, there is this method parseQuery() which makes the assumption of using ['id', 'ASC'] if an order option is not present. 

Can someone fix this? Or point me in the right direction - in case I can help. Thanks in advance.

**Comment by p2c2e** [comment]
In worst, we may need to pass through the primary key attributes taken from **model.primaryKeyAttributes** through the call stack.

**Comment by nicgirault** [comment]
Sorry for the delay to answer... we are not used to maintain open source packages and definitely have an improvement area here. react-admin do rely on an id attribute, this is why we rely on it (the primary use case for this package is to be react-admin compatible). We also have use cases where tables don't have an id column. In this case we duplicate the attribute in the model definition:

```javascript
Template.init(
    {
      id: {
        field: 'name',
        type: DataTypes.STRING,
      },
      name: {
        type: DataTypes.STRING,
        primaryKey: true,
      },
      ...
    },
    {
      tableName: 'template',
      sequelize: sequelize,
    }
  )
```

Would it solve your problem?

**Comment by nicgirault** [comment]
Closing due to low activity
